# Generated by Django 5.0.6 on 2024-07-02 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_recruit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
