# Generated by Django 5.0.6 on 2024-07-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_uploadfile_uploaded_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='previous_role',
        ),
    ]
