# Generated by Django 5.0.6 on 2024-07-05 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_rename_recruit_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='previous_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recruit.previousrole'),
            preserve_default=False,
        ),
    ]
