# Generated by Django 5.0.6 on 2024-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_resume_previous_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdesc',
            old_name='designation',
            new_name='jobpost',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='previous_role',
            new_name='worked_as',
        ),
        migrations.RemoveField(
            model_name='jobdesc',
            name='user',
        ),
        migrations.AddField(
            model_name='jobdesc',
            name='extracted_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_data',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
