# Generated by Django 5.0.6 on 2024-07-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_remove_resume_award_remove_resume_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobdesc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruit.jobdesc'),
            preserve_default=False,
        ),
    ]
