# Generated by Django 5.0.6 on 2024-07-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_jobdesc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
